### PR TITLE
Adding SPI pins for Thunderboard Sense 2.

### PR DESCRIPTION
**Pull request by ashok-rao**
Thunderboard Sense 2 platfrom from SiLabs needs an external SD card adapter wired into the SPI pins on the expansion headers on the board. This is also part of the Cloud Client porting requirements. This PR adds the SPI pins for this platform.

Tested with Kingston 8GB class 4 card, SD card SPI breakout board & the Cloud Client application on the thunderboard sense 2 platform. Successful connection/registration to Cloud screenshot below:

tb_sense_12_cloudclient_success

### CODE REVIEW

**Comment by ashok-rao** [comment]
@deepikabhavnani , @geky  I'm trying to build the tests for the SD card, but greentea is not building the FAT_FILESYSTEM tests. Any thoughts? My cmd: 
```
C:\Ashok\blinky\mbed-os-example-blinky>mbed test --compile -t ARM -m TB_SENSE_12 
``` 
.. I'm trying to build the tests in an example "blinky" directory..

And output:
```
Build successes:
  * TB_SENSE_12::ARM::MBED-BUILD
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-BASIC_TEST
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-BASIC_TEST_DEFAULT
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-CASE_ASYNC_VALIDATE
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-CASE_CONTROL_ASYNC
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-CASE_CONTROL_REPEAT
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-CASE_SELECTION
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-CASE_SETUP_FAILURE
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-CASE_TEARDOWN_FAILURE
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-CONTROL_TYPE
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-MINIMAL_ASYNC_SCHEDULER
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-MINIMAL_SCHEDULER
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-TEST_ASSERTION_FAILURE_TEST_SETUP
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-TEST_SETUP_CASE_SELECTION_FAILURE
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-FRAMEWORKS-UTEST-TESTS-UNIT_TESTS-TEST_SETUP_FAILURE
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-TESTS-FILESYSTEM-HEAP_BLOCK_DEVICE
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-TESTS-FILESYSTEM-MBR_BLOCK_DEVICE
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-TESTS-FILESYSTEM-UTIL_BLOCK_DEVICE
  * TB_SENSE_12::ARM::MBED-OS-TESTS-EVENTS-QUEUE
  * TB_SENSE_12::ARM::MBED-OS-TESTS-EVENTS-TIMING
  * TB_SENSE_12::ARM::MBED-OS-TESTS-INTEGRATION-BASIC
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-MBED-ATTRIBUTES
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-MBED-CALL_BEFORE_MAIN
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-MBED-CPP
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-MBED-DIV
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-MBED-STATIC_ASSERT
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-BASIC
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-EVENT_FLAGS
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-HEAP_AND_STACK
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-MAIL
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-MALLOC
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-MUTEX
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-QUEUE
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-RTOSTIMER
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-SEMAPHORE
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-SIGNALS
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-THREADS
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDMICRO-RTOS-MBED-TIMER
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDTLS-MULTI
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBEDTLS-SELFTEST
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-C_STRINGS
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-DEV_NULL
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-ECHO
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-FLASHIAP
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-GENERIC_TESTS
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-LP_TIMEOUT
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-LP_TIMER
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-RACE_TEST
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-RTC
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-SLEEP_LOCK
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-STL_FEATURES
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-TICKER
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-TIMEOUT
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_FUNCTIONAL-CALLBACK
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_FUNCTIONAL-CALLBACK_BIG
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_FUNCTIONAL-CALLBACK_SMALL
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_FUNCTIONAL-FUNCTIONPOINTER
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_HAL-FLASH
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_HAL-LP_TICKER
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_HAL-LP_US_TICKERS
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_HAL-RTC_TIME
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_HAL-SLEEP_MANAGER
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_HAL-SLEEP_MANAGER_RACECONDITION
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_HAL-TICKER


Build skips:
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-NETSOCKET-CELLULAR-GENERIC_MODEM_DRIVER-TESTS-UNIT_TESTS-DEFAULT
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-TESTS-FILESYSTEM-FAT_FILESYSTEM
  * TB_SENSE_12::ARM::MBED-OS-FEATURES-TESTS-FILESYSTEM-MULTIPART_FAT_FILESYSTEM
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-MEM_TRACE
  * TB_SENSE_12::ARM::MBED-OS-TESTS-MBED_DRIVERS-STATS
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-CONNECTIVITY
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-GETHOSTBYNAME
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-IP_PARSING
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-SOCKET_SIGIO
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-TCP_ECHO
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-TCP_ECHO_PARALLEL
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-TCP_HELLO_WORLD
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-TCP_PACKET_PRESSURE
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-TCP_PACKET_PRESSURE_PARALLEL
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-UDP_DTLS_HANDSHAKE
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-UDP_ECHO
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-UDP_ECHO_PARALLEL
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-UDP_PACKET_PRESSURE
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETSOCKET-UDP_PACKET_PRESSURE_PARALLEL
  * TB_SENSE_12::ARM::MBED-OS-TESTS-NETWORK-WIFI

C:\Ashok\blinky\mbed-os-example-blinky>
```

**Comment by deepikabhavnani** [comment]
I see MBED_EXTENDED_TESTS define required to build "MBED-OS-FEATURES-TESTS-FILESYSTEM-FAT_FILESYSTEM" test https://github.com/ARMmbed/mbed-os/blob/master/features/TESTS/filesystem/fat_filesystem/main.cpp#L28

SD Fat file system test are not present in mbed-os repository. Please include sd-driver library.
Test folder: https://github.com/ARMmbed/sd-driver/tree/master/TESTS

**Comment by ashok-rao** [comment]
Thanks @deepikabhavnani . I could run 2/3 tests successfully. The "filesystem-basic" is failing however. It's a Kingston 8GB class 4 card. I also formatted it freshly with SDFormatter utility to FAT32. Could you please take a look at the attached logs to check if you see something suspicious? Thanks!

[sd_driver_GT_Logs.txt](https://github.com/ARMmbed/sd-driver/files/1458426/sd_driver_GT_Logs.txt)

**Comment by deepikabhavnani** [comment]
As per the log data device is detected properly and fails in comparison test.

[1510245840.83][CONN][RXD] write 0180416800:2048 aad8573abd84e79e5e3684fa5519aabb...
[1510245841.15][CONN][RXD] read  0180416800:2048 31da16e3fefcdff1f219ed2637dcc7c1...
[1510245841.15][CONN][RXD] error 0180416800:2048 ffffffffffffffffffffffffffffffff

Looks like some issue. I have added some additional test for SD-driver (created https://github.com/ARMmbed/sd-driver/pull/66).

Please try those and let me know the results.

**Comment by ashok-rao** [comment]
@deepikabhavnani , results are still the same with PR #66 applied as well. Attaching some logs if it helps. Any thoughts? Thank you.
[sd_driver_PR66.txt](https://github.com/ARMmbed/sd-driver/files/1460866/sd_driver_PR66.txt)

**Comment by deepikabhavnani** [comment]
@ashok-rao - All tests are failing for me, as per filesystem test log no test was performed because FSFAT_SDCARD_INSTALLED define was not present. Test expects the define from mbed_app.json and we have added it in mbed_lib.json. Will add PR to fix this.

```
[1510673499.29][CONN][RXD]
[1510673499.29][CONN][INF] found KV pair in stream: {{__testcase_finish;FSFAT_FOPEN_TEST_10: remove() test.;1;0}}, queued...
[1510673499.31][CONN][RXD] >>> Running case #10: 'FSFAT_FOPEN_TEST_11: rename().'...
**[1510673499.31][CONN][RXD] Null test**
[1510673499.31][CONN][RXD] >>> 'FSFAT_FOPEN_TEST_11: rename().': 1 passed, 0 failed
[1510673499.31][CONN][RXD]
[1510673499.31][CONN][INF] found KV pair in stream: {{__testcase_start;FSFAT_FOPEN_TEST_11: rename().}}, queued...
[1510673499.31][CONN][INF] found KV pair in stream: {{__testcase_finish;FSFAT_FOPEN_TEST_11: rename().;1;0}}, queued...
[1510673499.33][CONN][RXD] >>> Running case #11: 'FSFAT_FOPEN_TEST_12: opendir(), readdir(), closedir() test.'...
**[1510673499.33][CONN][RXD] Null test** 
```
After fixing the define check filesystem test are failing as well. Will update further

**Comment by ashok-rao** [comment]
Thanks @deepikabhavnani . Will await your findings!

**Comment by ashok-rao** [comment]
Commit 376ddcc modifies the SPI frequency for this target by slowing it down due to a HW limitation on the EFR32 (HFCLK = 38.4MHz and SPI clock = HFCLK / 4 ).
With this change all tests for SD driver are passing. Logs are attached below:
[sd_driver_GT_Logs_PASS.txt](https://github.com/ARMmbed/sd-driver/files/1478397/sd_driver_GT_Logs_PASS.txt)

@deepikabhavnani , over to you for review and merge if all OK! Thank you.

**Pull request merged**
