### PR TITLE
Support SD card driver on DISCO_F429ZI

### PR DESCRIPTION
**Pull request by soramame21**
This PR is tested using following environment.

 - ARMmbed/mbed-cloud-client-example-internal with esp8266.
 - mbed-cloud-sdk-javascript-quickstart

### CODE REVIEW

**Comment by deepikabhavnani** [comment]
@soramame21 - Please share the test results for DISCO_F429ZI device

**Comment by marcuschangarm** [comment]
@soramame21 have you tested this while using the ethernet port and not the wifi?

I was under the impression that the F429 had a pin conflict with the CI shield and ethernet port.

**Comment by soramame21** [comment]
@marcuschangarm sorry for delayed answer. I tested it using wifi. Disco_F429 doesn't support Arduino header, so you can use any pin. yes, Nucleo_F429 supports Arduino header, and D11 cannot work with ETH and SPI together as default. I made a HW patch for removing the conflict on Nucleo_F429 enabled SPI and ETH working in parallel.

**Comment by JanneKiiskila** [comment]
Are we ready to merge? @marcuschangarm

**Comment by soramame21** [comment]
@deepikabhavnani @marcuschangarm Sorry for delayed reply. I uploaded the sd driver test result. please review.
[sd-driver-on-disco-f429zi-test-result.txt](https://github.com/ARMmbed/sd-driver/files/1550640/sd-driver-on-disco-f429zi-test-result.txt)

**Comment by JanneKiiskila** [comment]
So, let me get this clarified - does this change require, that one modifies every NUCLEO_F429ZI board to work with THESE configs? 

Right now we already have the F429ZI running in CI with the instructions in README.md.

```
        "SPI_CS": "D10",
        "SPI_MOSI": "D11",
        "SPI_MISO": "D12",
        "SPI_CLK": "D13",
```

I think we're then using those defines. Will this then mean we have to modify every HW? 
(I'm not sure I would like that).

**Comment by soramame21** [comment]
No, it's for DISCO_F429ZI only.
NUCLEO_F429ZI does support Arduino pin header, need to use D10 to D13.
but DISCO_F429ZI doesn't, it means Dxx named pins don't exist.

**Comment by JammuKekkonen** [comment]
NUCLEO_F429ZI is using PC_10, PC_11, PC_12 and PC_15 in the config. That's because D10 is conflicting with Ethernet. Readme and actual config are out of sync.

**Comment by soramame21** [comment]
Thanks for your notice. Both NUCLEO_F429ZI and DISCO_F429ZI are using the same set of SPI pins.
```
"SPI_MOSI": "PC_12",
"SPI_MISO": "PC_11",
"SPI_CLK":  "PC_10",
"SPI_CS":   "PA_15"
```

**Comment by marcuschangarm** [comment]
@JanneKiiskila I don't have a disco so can't test it, but I was told that it had the same problem as the nucleo wrt pin conflicts.

However, if @soramame21 can confirm that this works on the disco when using ethernet and sd card then that is great!

**Comment by soramame21** [comment]
@marcuschangarm @JanneKiiskila let me make a simple comparison between the 2 boards.

```
NUCLEO_F429ZI
  - build-in Ethernet I/F
  - Arduino pin header, means support Dxx pin name.
  - Conflict between Ethernet I/F and SPI pins on Arduino D11.
  - above conflict can be removed by a HW patch.
    Remove SB121 and close SB122 solder bridges on back side, then D11 can work as SPI MOSI, 
    and Ethernet can work concurrently. 
DISCO_F429ZI
  - no Ethernet I/F
  - no Arduino pin header, means doesn't support Dxx pin name.
  - no conflict of D11. because Arduino header is not supported, D11 pin and 
    Ethernet I/F doesn't exist.
```

**Pull request merged**
