### PR TITLE
Nucleo NUCLEO_F207ZG pin configuration

### PR DESCRIPTION
**Pull request by JaniSuonpera**
For SPI3.

### CODE REVIEW

**Comment by JanneKiiskila** [comment]
Should we add a picture to https://github.com/ARMmbed/sd-driver/tree/master/docs/pics as well?

**Comment by geky** [comment]
@JaniSuonpera, sorry, but while we're moving the block devices into mbed-os, we need to keep PRs frozen:
https://github.com/ARMmbed/mbed-os/pull/7774

You can either open a pr on mbed-os, or we'll look at moving this pr over when we go through marking the external repositories as obsolete.

**Comment by JaniSuonpera** [comment]
@JanneKiiskila Good idea. Pins are exaclty same than with NUCLEO_F429ZI

**Comment by JaniSuonpera** [comment]
@geky Would you add pin configuration for NUCLEO_F207ZG to mbed-os side?

**Comment by JanneKiiskila** [comment]
No need to make another drawing then, we can just reference to that same one.

**Comment by JanneKiiskila** [comment]
But, the README.md should be updated to indicate this same info applies to probably ALL of the similarly shaped boards from ST.

**Comment by JaniSuonpera** [comment]
Will be released trough mbed-os.

**Pull request closed without merging**
