### PR TITLE
Change mutex to PlatformMutex

### PR DESCRIPTION
**Pull request by deepikabhavnani**
Resolves: https://github.com/ARMmbed/sd-driver/issues/69

### CODE REVIEW

**Comment by deepikabhavnani** [comment]
@geky - Please review

**Comment by deepikabhavnani** [comment]
@geky - Lock function is not required, added just to have consistent code with mbed-os drivers.

**Comment by geky** [comment]
Hmm, I think most drivers have lock + unlock so that multiple consumers of the class can synchronize on hardware accesses. (Like SPI transactions).

**Comment by deepikabhavnani** [comment]
In that case, lock/unlock functions should be public right?

**Comment by geky** [comment]
I think the idea is you can extend the classes to provide a different synchronization interface. But for a non-transactional class each function is its own synchronization boundary.

cc @c1728p9 for his thoughts

**Pull request merged**
